### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by Gusi2406** [rstropek-teaching/contact-list-quiz-5ahif-Gusi2406#1]
http://contactlistif130012.azurewebsites.net/api/contacts
http://contactlistif130012.azurewebsites.net/api/contacts/findByName/Wolf

**Comment by rstropek** [comment]
@Gusi2406 Thank you for your homework. It contained two little mistakes. I added comments to your code to indicate the errors I found. Still, well done 👍 Your extra point is secured.

Please share my comments with the colleagues who you worked together with.

Greetings,
Rainer Stropek.
